name: Run Test Suite on PR or push to master

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    strategy:
      matrix:
        ruby: [ 2.5, 2.6, 2.7 ]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup Ruby ${{ matrix.ruby }}
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}

      - name: Build and run tests
        run: |
          echo "gem: --no-document" > ~/.gemrc
          gem install bundler
          bundle install --retry 3
          bundle exec rake test
